name: pack-git-solution
# Export solution from DEV environment
# unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'The solution name.'
        type: string
        default: PruebaExportacion       
      solution_outbound_folder:
        description: 'staging the unpacked solution folder before check-in *do not change*'
        type: string
        default: out/solutions/
      solution_source_folder: 
       description: 'folder name to be created and checked in *do not change*'
       type: string
       default: solutions/
env:
#edit your values here
  USER : 'admin@cicportaldemos.onmicrosoft.com'
  PASS : 'Cloud123!'
  ENVIRONMENT_URL: 'https://devcicportaldemos.crm4.dynamics.com'
  CLIENT_ID: '49d2e9c3-cb62-4f96-801a-7dacc4874cca'
  TENANT_ID: 'bb24ff0d-24a0-4146-851b-761c2ac27b24'

jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@0.4.0
      with:
        solution-folder: ${{ github.event.inputs.solution_source_folder}}/${{ github.event.inputs.solution_name }}
        solution-file: ${{ github.event.inputs.solution_outbound_folder}}/${{ github.event.inputs.solution_name }}.zip
        solution-type: Unmanaged
    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        user-name: ${{env.USER}}
        password-secret: ${{ env.PASS }}
        solution-file: ${{ github.event.inputs.solution_outbound_folder}}/${{ github.event.inputs.solution_name }}.zip
        force-overwrite: true
        publish-changes: true
    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
          environment-url: ${{env.ENVIRONMENT_URL}}
          user-name : ${{env.USER}}
          password-secret : ${{ env.PASS }}
          solution-name : ${{ github.event.inputs.solution_name }}
          solution-output-file : ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@0.4.0
      with:
              solution-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip
              solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
              solution-type: 'Unmanaged'
              overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
            solution-folder: ${{ github.event.inputs.solution_folder}}/${{ github.event.inputs.solution_name }}
            solution-target-folder: ${{ github.event.inputs.solution_target_folder}}/${{ github.event.inputs.solution_name }}
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            allow-empty-commit: true
